fastlane_version '2.196.0'

before_all do
  ensure_git_branch(branch: 'main')
  ensure_git_status_clean
  git_pull
end

platform :ios do
    desc 'Fetch certificates and provisioning profiles'
    lane :certificates do
      match(app_identifier: 'lucy.jmsims.spot', type: 'development', readonly: true)
      match(app_identifier: 'lucy.jmsims.spot', type: 'appstore', readonly: true)
    end

    desc 'Build the iOS application.'
    private_lane :build do
        certificates
        increment_build_number(xcodeproj: './ios/myviroapp.xcodeproj')
        gym(scheme: 'SpotApp', project: './ios/myviroapp.xcodeproj')
    end

    desc 'Ship to Testflight.'
    lane :beta do
        build
        pilot
        commit_version_bump(message: 'Bump build', xcodeproj: './ios/myviroapp.xcodeproj')
        push_to_git_remote
  end
end